import '../app_texts/app_texts.dart';

const  Map<String, String> ar ={

AppTexts. onBoardingTitle : 'نبحث بدقة لنقدم لك العقار الذي تستحقه',
AppTexts. onBoardingTitle1 : 'عملاء مميزون ونتائج مبهرة !',
AppTexts. onBoardingTitle2 : 'عندما تصبح الأحلام منزلاً !',

AppTexts. onBoardingDescription :
    'طريقك الأسرع لإيجاد العقار الذي تبحث عنه',
AppTexts. onBoardingDescription1 :
    'نوفر لك الأسعار المناسبة لبيع وتأجير عقارك',
AppTexts. onBoardingDescription2 :
'نقدم أكثر ما تريد للعثور على منزللك المناسب',
    AppTexts. signUp : 'تسجيل مستخدم جديد',
AppTexts. explore : 'إستكشف',
AppTexts. signIn : 'تسجيل دخول',
AppTexts.pleaseEnterPhone:'الرجاء ادخال رقم الهاتف',
AppTexts.pleaseEnterPas:'قم بادخال كلمة المرور',
AppTexts.pleaseEnterName:'قم بادخال الاسم ',
AppTexts. myProfile : 'حسابي',
AppTexts. notifications : 'الإشعارات',
AppTexts. privacy : 'الأمان والخصوصية',
AppTexts. lang : 'اللغة',
AppTexts. help : 'المساعدة',
AppTexts. logout : 'تسجيل الخروج',
AppTexts. emptyCart : 'شاشة المفضلة فارغة',
AppTexts. emptyNotification : 'شاشة الإشعارات فارغة',
AppTexts. emptyCartDes : 'لا توجد عقارات مفضلة لك بعد , تصفح المزيد من العقارات واحفظ عقاراتك المفضلة هنا',
AppTexts.phoneNumber : 'رقم الجوال',
AppTexts.idNumber : 'رقم الهوية',
AppTexts.userPhoneNumber : '0597786890',
AppTexts.password : 'كلمة المرور',
AppTexts.forgetPassword : 'نسيت كلمة المرور',
AppTexts.resetPass : 'استرجاع كلمة المرور',
AppTexts.checkCode : 'التحقق من الرمز',
AppTexts. resend : 'إعادة إرسال الرمز',
AppTexts. newPass : 'كلمة مرور جديدة',
AppTexts. createNewPass : 'إنشاء كلمة مرور جديدة',
AppTexts. fullName : 'الاسم الكامل',
AppTexts. userName : 'محمد أحمد',
AppTexts. userEmail : 'ahmad@gmail.com',
AppTexts. email : 'البريد الالكتروني',
AppTexts. address : 'المكان (الموقع)',
AppTexts. userAddress : 'فلسطين - غزة - النصر',
AppTexts. dontHaveAccount : 'لا تمتلك حساب؟',
AppTexts. createAccount : 'قم بانشاء حساب ',
AppTexts.createNewAccount : 'إنشاء حساب جديد',
AppTexts.bycreateAccount : 'من خلال إنشاء حساب ، فإنك توافق على ',
AppTexts.terms : ' الشروط والأحكام',
AppTexts. ourOwn : 'الخاصة بنا',
AppTexts.alreadyHaveAccount : 'تمتلك حساب بالفعل؟',
AppTexts.dontWorry : 'لا تقلق ، ما عليك سوى كتابة رقم هاتفك وسنرسل رمز التحقق.',
AppTexts. congrats : 'تهانينا !',
AppTexts.ready : '''حسابك جاهز للإستخدام وسيتم
  توجيهك إلى الصفحة الرئيسية
  خلال ثواني .''',


AppTexts. searchSentance:'ابحث عن المكان الذي تحب أن تمتلكه',
AppTexts.exploreSentance:'استكشف العقارات المميزة',
AppTexts.buy:'شراء',
AppTexts.palestine:'فلسطين',
AppTexts.gaza:'غزة',
AppTexts.region:'الصناعة',
AppTexts.bookAppointment:'حجز موعد',
AppTexts.selectAppointment:'اختر موعد',
AppTexts. rent:'إيجار',
AppTexts. detailes:'التفاصيل',
AppTexts. detailesScreenTitle:'تفاصيل العقار',
AppTexts. aboutProperty:'عن هذا العقار',
AppTexts. searchLabel:'العنوان , المدينة',
AppTexts.  propertyDiscreption:'''بيت كامل للبيع مساحة الأرض 200 متر  مبني عليه طوابق كل طابق فيه 3 شقق مساحة الشقة  متر
  عمر البناء سنوات , اتجاه الشمال الشرقي من منطقة التفاح عمر البناء سنوات , اتجاه الشمال الشرقي من منطقة التفاح عمر البناء سنوات , اتجاه الشمال الشرقي من منطقة التفاح 
  عمر البناء سنوات , اتجاه الشمال الشرقي من منطقة التفاح ''',
AppTexts.filter:'التصفية',
AppTexts.house:'منزل',
AppTexts.apartment:'شقة',
AppTexts.building:'عمارة',
AppTexts.villa:'فيلا',
AppTexts.office:'مكاتب',
AppTexts.land:'أرض',
AppTexts.chalet:'شاليه',
AppTexts.chooseState:'أختر المحافظة',
AppTexts.chooseCity:'أختر المدينة',
AppTexts.estateType:'نوع العقار',
AppTexts.estateCost:'سعر العقار',
AppTexts. estateArea:'مساحة العقار (متر مربع)',
AppTexts.builtUpArea:'المساحة المبني عليها',
AppTexts.realEstateAgents:'الوكلاء العقاريين',
AppTexts. viewResults:'عرض النتائج',
AppTexts. bookNow:'احجز الأن',
AppTexts.home:'الرئيسة',
AppTexts.messages:'الرسائل',
AppTexts.favorite:'المفضلة',
AppTexts.settings:'الإعدادات',
AppTexts. helping1:  'الإبلاغ عن مشكلة واجهتك في التطبيق؟',
AppTexts. helping2:  'الإبلاغ عن عقار أو وكيل داخل التطبيق؟',
AppTexts. helping3:  'حجز موعد لمعاينة عقار ما؟',
AppTexts. helping4:  'تغيير لغة التطبيق؟',
AppTexts. helping5:  'التواصل مع الوكلاء ؟',




AppTexts.bed:'سرير',
AppTexts.bedroom:'غرف النوم',
AppTexts.bath:'حمام',
AppTexts.room:'غرفة',
AppTexts.livingRoom:'غرف المعيشة',
AppTexts.kitchen:'مطبخ',
AppTexts.garden:'حديقة',
AppTexts.stairs:'درج',
AppTexts.swimmingBool:'مسبح',
AppTexts.hall:'صالون',
AppTexts.airConditioner:'مكيف',
AppTexts.balcony:'بالكونة',
AppTexts.wifi:'Wi-fi',
AppTexts.elevator:'مصعد',
AppTexts.availableResults:'النتائج المتاحة',
AppTexts.contactWithAgent:'تواصل مع الوكيل',
    AppTexts.startChatting:'بدء الدردشة',


AppTexts.addProperty:'إضافة العقار',
    AppTexts.propertiesList:'قائمة العقارات',
    AppTexts. rate:'التقييم',
    AppTexts. take:'استلم',
    AppTexts. sell:'باع',
    AppTexts.findWithAgents:'العثور على أفضل مكان للعيش فيه مع توصيات العملاء .',
AppTexts.propertyLocation:'عنوان العقار',
AppTexts. agent:' الوكيل',
AppTexts.propertyProofImage:' صورة ثبوتية عن ملكية العقار',
AppTexts.idImage:' صورة الهوية',
AppTexts.percent:'نسبته',
AppTexts.dataSent:'تم إرسال البيانات  !',
AppTexts.saveAndSent:'حفظ و ارسال',
AppTexts.dataSentDescription:'''تم إرسال البيانات إلى المختصين وسيتم الرد
  عليك في مدة أقصاها يومين .''',





};