import '../app_texts/app_texts.dart';

const Map<String, String> en = {
AppTexts. onBoardingTitle : 'We search thoroughly to bring you the property you deserve',
AppTexts. onBoardingTitle1 : 'Wonderful Clients, Great Results!',
AppTexts. onBoardingTitle2 : 'When Dreams Become Home!',

AppTexts. onBoardingDescription:
'Your fastest way to find the property youre looking for',
AppTexts. onBoardingDescription1 :
'We provide you with the right prices for selling and renting your property',
AppTexts. onBoardingDescription2 :
'We offer what you need most to find your right home.',
  AppTexts.signUp: 'Register a new user',
  AppTexts.explore: 'Explore',
  AppTexts.signIn: 'Login',
  AppTexts.myProfile: 'My Account',
  AppTexts.pleaseEnterPhone: 'Please enter a phone number',
  AppTexts.pleaseEnterPas: 'Enter your password',
  AppTexts.pleaseEnterName:'Enter your Name ',

  AppTexts.notifications: 'Notifications',
  AppTexts.privacy: 'Security and Privacy',
  AppTexts.lang: 'Language',
  AppTexts.help: 'Help',
  AppTexts.logout: 'log out',
  AppTexts.emptyCart: 'favorites screen is empty',
  AppTexts.emptyNotification: 'Notification screen is empty',
  AppTexts.emptyCartDes:
      'There are no properties for you yet, browse more properties and save your favorite properties here',
  AppTexts.phoneNumber: 'Mobile Number',
  AppTexts.idNumber: 'ID number',
  AppTexts.userPhoneNumber: '0597786890',
  AppTexts.password: 'Password',
  AppTexts.forgetPassword: 'Forgot your password?',
  AppTexts.resetPass: 'Reset password',
  AppTexts.checkCode: 'Check Code',
  AppTexts.resend: 'resend the code',
  AppTexts.newPass: 'new password',
  AppTexts.createNewPass: 'Create a new password',
  AppTexts.fullName: 'full name',
  AppTexts.userName: 'Mohamed Ahmed',
  AppTexts.userEmail: 'ahmad@gmail.com',
  AppTexts.email: 'E-mail',
  AppTexts.address: 'place (location)',
  AppTexts.userAddress: 'Palestine - Gaza - Al Nasr',
  AppTexts.dontHaveAccount: 'Dont have an account?',
  AppTexts.createAccount: 'Create an account',
  AppTexts.createNewAccount: 'Create a new account',
  AppTexts.bycreateAccount: 'By creating an account you agree to',
  AppTexts.terms: 'Terms and Conditions',
  AppTexts.ourOwn: 'our',
  AppTexts.alreadyHaveAccount: 'Already have an account?',
  AppTexts.dontWorry:
      "Don't worry, just type in your phone number and we'll send a verification code.",
  AppTexts.congrats: 'Congratulations!',
  AppTexts.ready: '''Your account is ready to use and will be
Redirect you to the home page
within seconds.''',
  AppTexts.searchSentance: 'Find the place you love to own',
  AppTexts.exploreSentance: 'Explore Featured Properties',
  AppTexts.buy: 'Buy',
  AppTexts.bookAppointment: 'Book Appointment',
  AppTexts.selectAppointment: 'Select Appointment',
  AppTexts.rent: 'Rent',
  AppTexts.detailes: 'Details',
  AppTexts.detailesScreenTitle: 'property details',
  AppTexts.aboutProperty: 'About this Property',
  AppTexts.searchLabel: 'Address, city',
  AppTexts. palestine: 'Palestine',
  AppTexts.gaza: 'Gaza',
  AppTexts.region: 'Industry',
  AppTexts.propertyDiscreption:
      '''A complete house for sale, the land area is 200 meters, and it is built on floors, each floor contains 3 apartments, the area of ​​the apartment is one meter
The age of the building is in years, looking northeast from the Al-Tuffah area The age of the building is in years, looking northeast from the Al-Tuffah area The age of the building is in years, looking northeast from the Al-Tuffah area
The building is years old, looking northeast from Al-Tuffah area ''',
  AppTexts.filter: 'Filter',
  AppTexts.house: 'Home',
  AppTexts.apartment: 'Apartment',
  AppTexts.building: 'Building',
  AppTexts.villa: 'villa',
  AppTexts.office: 'Offices',
  AppTexts.land: 'Land',
  AppTexts.chalet: 'Chalet',
  AppTexts.chooseState: 'Choose State',
  AppTexts.chooseCity: 'Choose City',
  AppTexts.estateType: 'Property Type',
  AppTexts.estateCost: 'property price',
  AppTexts.estateArea: 'property area (sqm)',
  AppTexts.builtUpArea: 'Built-UpArea',
  AppTexts.realEstateAgents: 'Estate Agents',
  AppTexts.viewResults: 'View Results',
  AppTexts.bookNow: 'Book Now',
  AppTexts.bed: 'Bed',
  AppTexts.bedroom: 'Bedroom',
  AppTexts.bath: 'bath',
  AppTexts.room: 'Room',
  AppTexts.livingRoom: 'Living Rooms',
  AppTexts.kitchen: 'Kitchen',
  AppTexts.garden: 'Garden',
  AppTexts.stairs: 'stairs',
  AppTexts.swimmingBool: 'Swimming Pool',
  AppTexts.hall: 'Salon',
  AppTexts.airConditioner: 'Air Conditioner',
  AppTexts.balcony: 'Balcony',
  AppTexts.wifi: 'Wi-fi',
  AppTexts.elevator: 'elevator',
  AppTexts.availableResults: 'Available Results',
  AppTexts.contactWithAgent:'Contact with Agent',
AppTexts.startChatting:'Start Chatting',
  AppTexts.home: 'Home',
  AppTexts.messages: 'Messages',
  AppTexts.favorite: 'Favorites',
  AppTexts.settings: 'Settings',
  AppTexts.helping1: 'Report a problem you encountered in the app?',
  AppTexts.helping2: 'Report a property or agent within the app?',
  AppTexts.helping3: 'Book an appointment to view a property?',
  AppTexts.helping4: 'Change application language?',
  AppTexts.helping5: 'Communicate with agents?',
  AppTexts.addProperty: 'Add Property',
  AppTexts.propertyLocation: 'property address',
  AppTexts.agent: 'agent',
  AppTexts.propertyProofImage: 'Proof of property ownership',
  AppTexts.idImage: 'ID Image',
  AppTexts.percent: 'percentage',
  AppTexts.dataSent: 'Data sent!',
  AppTexts.saveAndSent: 'Save and Send',
  AppTexts.propertiesList:'Property List',
  AppTexts. rate: 'Rate',
  AppTexts. take: 'Take',
  AppTexts. sell: 'Sell',
  AppTexts.findWithAgents: 'Find the best place to live with customer recommendations.',
  AppTexts.dataSentDescription:
      '''The data has been sent to the specialists and they will respond
You must within a maximum period of two days.''',
};
